"""
apps/activities/models.py
Performance monitoring subsystem — captures user activity logs,
learning sessions, and productivity metrics over time intervals.
"""

from django.db import models
from django.conf import settings
from django.utils import timezone


class ActivityLog(models.Model):
    """
    Core activity log entry. Every learning session, task completion,
    or productive event is recorded here for analysis by the ML engine.
    """

    ACTIVITY_TYPE_CHOICES = [
        ('study', 'Study Session'),
        ('exercise', 'Exercise'),
        ('reading', 'Reading'),
        ('project', 'Project Work'),
        ('assessment', 'Assessment / Quiz'),
        ('networking', 'Networking'),
        ('reflection', 'Reflection / Journaling'),
        ('workshop', 'Workshop / Lecture'),
        ('other', 'Other'),
    ]

    MOOD_CHOICES = [
        (1, 'Very Unproductive'),
        (2, 'Unproductive'),
        (3, 'Neutral'),
        (4, 'Productive'),
        (5, 'Highly Productive'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='activity_logs'
    )
    goal = models.ForeignKey(
        'goals.Goal',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='activity_logs'
    )
    milestone = models.ForeignKey(
        'goals.Milestone',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='activity_logs'
    )
    skill = models.ForeignKey(
        'skills.UserSkill',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='activity_logs'
    )

    activity_type = models.CharField(max_length=20, choices=ACTIVITY_TYPE_CHOICES)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    # Time tracking
    started_at = models.DateTimeField()
    ended_at = models.DateTimeField(null=True, blank=True)
    duration_minutes = models.PositiveIntegerField(default=0)

    # Productivity metrics
    productivity_score = models.PositiveSmallIntegerField(
        choices=MOOD_CHOICES, default=3,
        help_text='Self-rated productivity (1–5)'
    )
    focus_level = models.PositiveSmallIntegerField(
        default=3, help_text='Focus level 1–5'
    )
    outcome_notes = models.TextField(blank=True, help_text='What did you achieve?')

    # Progress updates
    goal_progress_delta = models.FloatField(
        default=0.0,
        help_text='How much did this session advance the linked goal?'
    )
    skill_score_delta = models.FloatField(
        default=0.0,
        help_text='Estimated skill score change from this session'
    )

    tags = models.JSONField(default=list, blank=True)
    logged_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-started_at']
        indexes = [
            models.Index(fields=['user', 'started_at']),
            models.Index(fields=['user', 'activity_type']),
            models.Index(fields=['user', 'goal']),
        ]

    def __str__(self):
        return f"{self.user.username} — {self.title} ({self.started_at.date()})"

    def save(self, *args, **kwargs):
        # Auto-calculate duration if both timestamps present
        if self.started_at and self.ended_at and not self.duration_minutes:
            delta = self.ended_at - self.started_at
            self.duration_minutes = int(delta.total_seconds() / 60)
        super().save(*args, **kwargs)

    @property
    def hour_of_day(self):
        """Used by the ML engine to identify peak productivity hours."""
        return self.started_at.hour

    @property
    def day_of_week(self):
        return self.started_at.weekday()  # 0=Monday


class ProductivitySnapshot(models.Model):
    """
    Daily aggregated productivity snapshot — generated by Celery task.
    Feeds the trend charts and the ML recommendation engine.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='productivity_snapshots'
    )
    date = models.DateField()

    total_sessions = models.PositiveSmallIntegerField(default=0)
    total_minutes = models.PositiveIntegerField(default=0)
    avg_productivity = models.FloatField(default=0.0)
    avg_focus = models.FloatField(default=0.0)
    goals_advanced = models.PositiveSmallIntegerField(default=0)
    skills_practised = models.PositiveSmallIntegerField(default=0)

    # Computed by the ML engine
    predicted_next_day_score = models.FloatField(null=True, blank=True)

    class Meta:
        unique_together = [('user', 'date')]
        ordering = ['-date']

    def __str__(self):
        return f"{self.user.username} — {self.date}: {self.avg_productivity:.1f}/5"
