# Generated by Django 4.2.13 on 2026-06-24 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('deadline', 'Deadline Alert'), ('skill_gap', 'Skill Gap'), ('habit', 'Habit Building'), ('schedule', 'Schedule Optimisation'), ('peer', 'Peer Insight'), ('resource', 'Resource Suggestion')], max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('action_label', models.CharField(default='Take action', max_length=100)),
                ('icon', models.CharField(default='ti-bulb', max_length=50)),
                ('confidence', models.FloatField(default=1.0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='goals.goal')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='skills.userskill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
