# Generated by Django 4.2.13 on 2026-06-24 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain_type', models.CharField(choices=[('technical', 'Technical'), ('academic', 'Academic'), ('soft_skills', 'Soft Skills'), ('leadership', 'Leadership'), ('creative', 'Creative'), ('health', 'Health & Fitness')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='ti-brain', max_length=50)),
                ('color_hex', models.CharField(default='#2563EB', max_length=7)),
                ('is_global', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['domain_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.FloatField(default=0.0)),
                ('target_score', models.FloatField(default=80.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_assessed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to='skills.skilldomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_score'],
                'unique_together': {('user', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='SkillScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('delta', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='skills.userskill')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
