# Generated by Django 4.2.13 on 2026-06-24 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sessions', models.PositiveSmallIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('avg_productivity', models.FloatField(default=0.0)),
                ('avg_focus', models.FloatField(default=0.0)),
                ('goals_advanced', models.PositiveSmallIntegerField(default=0)),
                ('skills_practised', models.PositiveSmallIntegerField(default=0)),
                ('predicted_next_day_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('study', 'Study Session'), ('exercise', 'Exercise'), ('reading', 'Reading'), ('project', 'Project Work'), ('assessment', 'Assessment / Quiz'), ('networking', 'Networking'), ('reflection', 'Reflection / Journaling'), ('workshop', 'Workshop / Lecture'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.PositiveSmallIntegerField(choices=[(1, 'Very Unproductive'), (2, 'Unproductive'), (3, 'Neutral'), (4, 'Productive'), (5, 'Highly Productive')], default=3, help_text='Self-rated productivity (1–5)')),
                ('focus_level', models.PositiveSmallIntegerField(default=3, help_text='Focus level 1–5')),
                ('outcome_notes', models.TextField(blank=True, help_text='What did you achieve?')),
                ('goal_progress_delta', models.FloatField(default=0.0, help_text='How much did this session advance the linked goal?')),
                ('skill_score_delta', models.FloatField(default=0.0, help_text='Estimated skill score change from this session')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='goals.goal')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='skills.userskill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='activities__user_id_4b9638_idx'), models.Index(fields=['user', 'activity_type'], name='activities__user_id_8d348e_idx'), models.Index(fields=['user', 'goal'], name='activities__user_id_9eeb68_idx')],
            },
        ),
    ]
