# Generated by Django 4.2.13 on 2026-06-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='Optional skill this goal is helping to improve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='skills.userskill'),
        ),
    ]
